apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::354059412288:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UZCOF54HEV85
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::354059412288:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T12:59:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8586"
  uid: d0683ab2-175c-4d46-8ef2-b2334bcdac47
